version: 0.2

env:
  variables:
    IMAGE_NAME: "simple-python-flask-app"
    IMAGE_TAG: "latest"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/docker_username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/docker_password
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/registry_url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Logging in to Docker registry..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Build started on `date`"
      - IMAGE_NAME="simple-python-flask-app"
      - IMAGE_TAG="latest"
      # Trim extra whitespace/newlines from environment variables
      - CLEAN_REGISTRY_URL=$(echo "$DOCKER_REGISTRY_URL" | tr -d '\n' | tr -d '\r' | xargs)
      - CLEAN_USERNAME=$(echo "$DOCKER_REGISTRY_USERNAME" | tr -d '\n' | tr -d '\r' | xargs)
      - FULL_IMAGE_NAME="${CLEAN_REGISTRY_URL}/${CLEAN_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}"
      - echo "Building Docker image $FULL_IMAGE_NAME"
      - docker build -t "$FULL_IMAGE_NAME" .
      - echo "Pushing Docker image..."
      - docker push "$FULL_IMAGE_NAME"

  post_build:
    commands:
      - echo "Build completed successfully on `date`"